### ISSUE TITLE
The Swift.package not work

### ISSUE THREAD

**Issue by priore** [sonsongithub/HTMLSpecialCharacters#2]
![Schermata 2021-02-19 alle 22 54 36](https://user-images.githubusercontent.com/1537350/108565984-f22d0700-7305-11eb-81e4-3fc2e7d8a9db.jpg)

**Comment by sonsongithub** [comment]
Thank you for reporting. I updated it. Please use 1.3.9.

**Comment by priore** [comment]
is a good job, thanks to you 👍
